channels:
  # Define conda channels here.
  - conda-forge

dependencies:
  # Define conda packages here.
  # If available, always prefer the conda version of a package.
  # Installation will be faster and more efficient.
  # https://anaconda.org/search
  - python=3.10.13
  - tesseract=5.3.0

  - pip=22.1.2
  - pip:
      # Define pip packages here.
      # https://pypi.org/
      - rpaframework==28.1.0 # https://rpaframework.org/releasenotes.html
      - rpaframework-recognition==5.2.3
      - robocorp==1.4.3
